sudo: required

services:
  - docker

before_install:
  - docker build -t mistre83/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mistre83/react-test npm run test -- --coverage

after_success:
  - docker build -t mistre83/multi-client ./client
  - docker build -t mistre83/multi-nginx ./nginx
  - docker build -t mistre83/multi-server ./server
  - docker build -t mistre83/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mistre83/multi-client
  - docker push mistre83/multi-nginx
  - docker push mistre83/multi-server
  - docker push mistre83/multi-worker